app:
  name: Tokenizer
  version: 1.0.0

logging:
  level:
    root: INFO

env:
  token:
    expiry: 600000 # 10 minutes in milliseconds
    key: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb

server:
  port: 8081

spring:
  security:
    user:
      name: user
      password: user